# Generated by Django 5.1.1 on 2024-09-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feature_image',
            new_name='featured_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
