# Generated by Django 5.1.1 on 2024-09-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_rename_feature_image_post_featured_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='views_count',
            new_name='view_count',
        ),
    ]
